# One-time (or "run again whenever build/ gets deleted/regenerated") setup so this project's
# generated build/FacadeDdsBridge.sln can be opened and built DIRECTLY in Visual Studio 2022's
# IDE (F7 / Ctrl+Shift+B) -- not just via build.ps1's command line.
#
# Why this is needed: build.ps1 passes /p:VCToolsVersion=14.44.35207 as a one-off MSBuild
# property on its own `cmake --build ...` invocation (see that script's own comments for why --
# fastddsd-3.6.lib was built with MSVC toolset 14.44, this machine's default toolset resolves
# to a different sub-version, e.g. 14.33, and linking against it then fails with 9 unresolved
# CRT-internal symbols: _Cnd_timedwait_for_unchecked, __std_search_1, __std_mismatch_1,
# __std_min_element_4, etc). That property is passed ONLY for that one build.ps1-driven build --
# it is not written into the .vcxproj files, so opening the .sln in Visual Studio and building
# there does NOT get it, and hits the exact same link errors. CMake's own generator-toolset
# flags (-T version=14.44 and variants) were already tried and confirmed NOT to inject
# <VCToolsVersion> into the generated .vcxproj on this CMake/VS combination (see build.ps1's
# comments) -- so this script uses the standard, generator-independent MSBuild mechanism
# instead: a Directory.Build.props file placed at the root of the generated build/ tree.
# MSBuild (both the CLI and Visual Studio's own IDE build, which is MSBuild underneath even for
# C++ .vcxproj) automatically discovers and merges Directory.Build.props from every ancestor
# directory of each project file being built, so ONE copy at build/'s root applies to
# FacadeDdsBridge.vcxproj, FacadeDdsBridgeSmokeTest.vcxproj, and the nested
# thirdparty/librtmp/rtmp_min.vcxproj / thirdparty/libmpeg/mpeg_min.vcxproj alike.
#
# Usage: powershell -ExecutionPolicy Bypass -File Setup-VisualStudio.ps1
# Then open build\FacadeDdsBridge.sln in Visual Studio 2022 and build normally.

param(
    [string]$VCToolsVersion = "14.44.35207",
    # F5/Local Windows Debugger default for FacadeDdsBridgeSmokeTest.exe -- opens PublishUi.cpp's
    # GUI (폴더 선택 + 드론 콤보 + 발행/정지/리셋), the thing actually worth hitting F5 on
    # repeatedly during publish/RTMP work now. Previously this pointed straight at
    # `--publish-facade "D:\...\facades\TOP" rtmp://.../live/front 2` (the headless CLI
    # orchestration mode, no window at all) -- that was fine before PublishUi.cpp existed, but
    # left stale afterward: F5 kept running the old headless path instead of the new GUI, which
    # from the outside looked exactly like "the UI got deleted" even though the code was there.
    # For the same headless run, use:
    #   --publish-facade "D:\ClaudePr\CheckCrack\facades\TOP" rtmp://192.168.100.224:1935/live/front 2
    # (absolute facade path required there -- not the relative "facades\TOP" used from a
    # repo-root terminal -- because Visual Studio's default debugger working directory is the
    # target's output dir (build\Debug), not the repo root; fps=2 because RtmpPublisher.cpp's
    # send loop paces each FLV tag by its own embedded timestamp and JpegFacadePublisher.cpp
    # bakes 1/fps seconds of duration into each frame, so fps=2 is what actually produces "one
    # frame every 500ms", not a separate throttle knob).
    [string]$SmokeTestDebugArgs = '--publish-ui'
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BuildDir = Join-Path $ScriptDir "build"

# Generate (or refresh) the Visual Studio solution -- same CMake invocation build.ps1 uses for
# its own configure step, kept in sync with that script deliberately (FASTDDS_ROOT/
# FFMPEG_DEV_ROOT default to tools/Module/FastDDSGen/FastDDS and tools/libffmpeg, see
# CMakeLists.txt -- override with -DFASTDDS_ROOT=.../-DFFMPEG_DEV_ROOT=... if needed).
cmake -S $ScriptDir -B $BuildDir -G "Visual Studio 17 2022" -A x64

$propsPath = Join-Path $BuildDir "Directory.Build.props"
$propsContent = @"
<Project>
  <!-- Generated by Setup-VisualStudio.ps1, DO NOT hand-edit (re-run that script instead).
       Makes Visual Studio's own IDE build use the same MSVC sub-version build.ps1's command
       line build passes via /p:VCToolsVersion, so opening this .sln directly in VS 2022 and
       building there links against fastddsd-3.6.lib correctly instead of hitting unresolved
       CRT-internal symbols. -->
  <PropertyGroup>
    <VCToolsVersion>$VCToolsVersion</VCToolsVersion>
  </PropertyGroup>
</Project>
"@
Set-Content -LiteralPath $propsPath -Value $propsContent -Encoding utf8

# F5 / "Local Windows Debugger" command-line args for FacadeDdsBridgeSmokeTest -- a plain
# `cmake -S -B` only ever CREATES this file if it's missing, never overwrites an existing one
# (it's Visual Studio's own per-user debug-settings file, not something CMake manages once
# present), so this is safe to write every time this script runs without fighting CMake.
$smokeTestUserPath = Join-Path $BuildDir "FacadeDdsBridgeSmokeTest.vcxproj.user"
$smokeTestUserContent = @"
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <LocalDebuggerCommandArguments>$SmokeTestDebugArgs</LocalDebuggerCommandArguments>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
  </PropertyGroup>
</Project>
"@
Set-Content -LiteralPath $smokeTestUserPath -Value $smokeTestUserContent -Encoding utf8

Write-Host ""
Write-Host "OK -- wrote $propsPath (VCToolsVersion=$VCToolsVersion)."
Write-Host "OK -- wrote $smokeTestUserPath (F5 on FacadeDdsBridgeSmokeTest runs: $SmokeTestDebugArgs)."
Write-Host "Open $BuildDir\FacadeDdsBridge.sln in Visual Studio 2022 and build normally (F7 / Ctrl+Shift+B)."
Write-Host "Re-run this script any time build\ is deleted/regenerated by a plain 'cmake -S -B' (that would wipe Directory.Build.props too)."
